# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - chore
      - dependencies
    groups:
      minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      major:
        applies-to: version-updates
        update-types:
          - major
