name: Test

on: [push, workflow_dispatch]

permissions:
  contents: write

concurrency:
  group: ${{github.ref}}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Bundle and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm test
